pipelines:
  default:
    - step:
        name: Test with eQual dev-2.0
        image: php:8.3-fpm
        artifacts:
          - artifacts/**
        services:
          - mysql
        script:
          #memo - current directory is /opt/atlassian/pipelines/agent/build
          # Install dependencies
          - apt-get update && apt-get -y install git libzip-dev libicu-dev default-mysql-client
          - docker-php-ext-install pdo pdo_mysql mysqli zip intl
          - docker-php-ext-enable mysqli
          # Create a directory for artifacts
          - mkdir -p artifacts
          - mkdir -p /var/www/html
          - rm -rf /var/www/html/*
          - git config --global --add safe.directory '*'
          # Clone the eQual framework repository
          - git clone https://github.com/equalframework/equal.git /var/www/html
          - git -C /var/www/html checkout dev-2.0
          # Remove the 'packages' directory
          - mv /var/www/html/packages /var/www/html/packages.core
          # Copy local files (repository) to 'packages' directory
          - cp -r . /var/www/html/packages
          # Restore the equal core package
          - cp -r /var/www/html/packages.core/core /var/www/html/packages/core
          # Verify the content of the package dir
          - ls -hal /var/www/html/packages
          # Run equal commands for testing and initialization
          - php /var/www/html/run.php --do=init_fs
          - php /var/www/html/run.php --do=test_fs-consistency
          - php /var/www/html/run.php --do=test_db-connectivity
          - php /var/www/html/run.php --do=init_db
          - php /var/www/html/run.php --do=init_package --package=core --ignore_platform=true
          # create temp config file for init with FMT specific constants
          - |
            echo "{\"DEFAULT_LANG\": \"fr\", \"FMT_INSTANCE_TYPE\": \"agency\", \"FMT_API_URL_EDMS\": \"http://localhost/\", \"FMT_API_URL_GLOBAL\": \"http://localhost/\", \"MINDEE_API_KEY\": \"\"}" > /var/www/html/config/config.json
          - set +e ; php /var/www/html/run.php --do=init_package --package=fmt --import=true --ignore_platform=true ; export FAILING=$? ; set -e
          - cp /var/www/html/log/equal.log artifacts/equal.log
          - if [ "$FAILING" -ne 0 ]; then exit $FAILING; fi
          # create a config file with FMT specific constants & specific services
          - |
            echo "{\"DEFAULT_LANG\": \"fr\", \"FMT_INSTANCE_TYPE\": \"agency\", \"FMT_API_URL_EDMS\": \"http://localhost/\", \"FMT_API_URL_GLOBAL\": \"http://localhost/\", \"MINDEE_API_KEY\": \"\", \"SERVICE_ORM_COLLECTION_CLASS\": \"fmt\\\\orm\\\\Collection\", \"SERVICE_ACCESS_ACCESSCONTROLLER\": \"fmt\\\\access\\\\AccessController\"}" > /var/www/html/config/config.json
          # Verify the content of the file
          - cat /var/www/html/config/config.json
          - set +e ; php /var/www/html/run.php --do=init_package --package=fmt --force=true --import=false --demo=true ; export FAILING=$? ; set -e
          - cp /var/www/html/log/equal.log artifacts/equal.log
          - if [ "$FAILING" -ne 0 ]; then exit $FAILING; fi
          # Run tests
          - set +e ; php /var/www/html/run.php --do=test_package --package=fmt ; export FAILING=$? ; set -e
          # Dump main log to artifacts
          - if [ "$FAILING" -ne 0 ]; then cp /var/www/html/log/equal.log artifacts/equal.log; fi
          # Exit according to returned code
          - exit $FAILING
definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: test
        MYSQL_DATABASE: equal
