<?php
/*
    This file is part of Symbiose Community Edition <https://github.com/yesbabylon/symbiose>
    Some Rights Reserved, Yesbabylon SRL, 2020-2025
    Licensed under GNU AGPL 3 license <http://www.gnu.org/licenses/>
*/

namespace fmt\core\followup;

class TaskModel extends \core\followup\TaskModel {

    public static function getDescription(): string {
        return "A task is generated from a task model when a purchase invoice is created or change status.";
    }

    public static function getColumns(): array {
        return [

            'entity' => [
                'type'              => 'string',
                'description'       => 'Namespace of the concerned entity.',
                'selection'         => [
                    'purchase\accounting\invoice\PurchaseInvoice'
                ],
                'required'          => true
            ],

            'trigger_event_id' => [
                'type'              => 'many2one',
                'foreign_object'    => 'fmt\core\followup\TaskEvent',
                'description'       => "The trigger event associated with the task model.",
                'required'          => false
            ],

            'deadline_event_id' => [
                'type'              => 'many2one',
                'foreign_object'    => 'fmt\core\followup\TaskEvent',
                'description'       => "The deadline event associated with the task model.",
                'domain'            => ['event_type', '=', 'date_field']
            ],

            'tasks_ids' => [
                'type'              => 'one2many',
                'foreign_object'    => 'fmt\core\followup\Task',
                'foreign_field'     => 'task_model_id',
                'description'       => "The purchase invoice tasks generated by the task model."
            ]

        ];
    }

    public static function getConstraints(): array {
        return [

            'entity' => [
                'not_allowed' => [
                    'message'   => 'Entity must be "purchase\accounting\invoice\PurchaseInvoice".',
                    'function'  => function ($entity, $values) {
                        return in_array($entity, ['purchase\accounting\invoice\PurchaseInvoice']);
                    }
                ]
            ]

        ];
    }
}
