<?php
/*
    Developed by Yesbabylon - https://yesbabylon.com
    (c) 2025-2026 Yesbabylon SA
    Licensed under the GNU AGPL v3 License - https://www.gnu.org/licenses/agpl-3.0.html
*/
namespace identity;

use equal\data\DataGenerator;
use infra\server\Instance;

class User extends \core\User {

    public static function getName() {
        return 'User';
    }

    public static function constants() {
        return ['AUTH_SECRET_KEY', 'FMT_INSTANCE_TYPE'];
    }

    public static function getColumns() {
        return [

            'name' => [
                'type'              => 'computed',
                'result_type'       => 'string',
                'description'       => "The name of the User.",
                'relation'          => ['identity_id' => 'name'],
                'store'             => true,
                'readonly'          => true
            ],

            'uuid' => [
                'type'              => 'string',
                'usage'             => 'text/plain:36',
                // #memo - commented for testing because items are on the same instance
                // #todo - uncomment for PROD
                // 'unique'            => true,
                'description'       => 'Unique identifier from the Master instance.'
            ],

            /*
                Following `source_*` fields apply to imported protected entities.
            */

            'source' => [
                'type'              => 'string',
                'description'       => 'The source the Identity originated from.',
                'selection'         => [
                    'manual',           // manual creation
                    'internal',         // identity generated by the software (imported, sync, ...)
                    'external'          // identity retrieved from an external source (API, ...)
                ],
                'default'           => 'manual'
            ],

            'source_type' => [
                'type'              => 'string',
                'selection'         => [
                    'eid',
                    'iam_auth',
                    'registry',
                    'third_party',
                    'manual'
                ],
                'default'           => 'manual',
                'description'       => 'Type of source (eid, registry, manual, etc.)',
                'help'              => 'Indicates how the identity data was obtained. In case of manual encoding, there is no proof for that value.',
            ],

            'source_origin' => [
                'type'              => 'string',
                'description'       => 'Detailed origin of the source (e.g. BCE, itsme, employer).',
                'help'              => 'Specifies the originating system, registry or third party.',
            ],

            'source_date' => [
                'type'              => 'datetime',
                'description'       => 'Date when the identity information was collected or encoded.',
                'help'              => 'Used to assess the freshness of the information.',
            ],

            'source_verification_status' => [
                'type'              => 'string',
                'selection'         => [
                    'pending',
                    'rejected',
                    'conflict',
                    'verified',
                ],
                'default'           => 'pending',
                'description'       => 'Status of the verification of the source (validity of the data).',
            ],

            'instance_id' => [
                'type'              => 'many2one',
                'foreign_object'    => 'infra\server\Instance',
                'description'       => 'Instance the object relates to (origin).',
                'dependents'        => ['instance_uuid']
            ],

            'instance_uuid' => [
                'type'              => 'computed',
                'result_type'       => 'string',
                'store'             => true,
                'instant'           => true,
                'relation'          => ['instance_id' => 'uuid'],
                'onupdate'          => 'onupdateInstanceUuid',
                'description'       => 'UUID of the origin instance the object comes from.'
            ],

            'identity_id' => [
                'type'              => 'many2one',
                'foreign_object'    => 'identity\Identity',
                'domain'            => ['type', '=', 'IN'],
                'description'       => 'The identity the user relates to.',
                'help'              => 'The identity that this user relates to on the current instance. If set, the user details (name, email, etc.) will be synchronized from the identity.',  
                'onupdate'          => 'onupdateIdentityId',
                'dependents'        => ['name', 'employee_id', 'identity_uuid']
            ],

            'identity_uuid' => [
                'type'              => 'computed',
                'result_type'       => 'string',
                'store'             => true,
                'instant'           => true,
                'relation'          => ['identity_id' => 'uuid'],
                'description'       => 'Identity the object relates to.',
            ],

            'setting_values_ids' => [
                'type'              => 'one2many',
                'foreign_object'    => 'core\setting\SettingValue',
                'foreign_field'     => 'user_id',
                'description'       => 'List of settings that relate to the user.'
            ],

            'owner_identity_id' => [
                'type'              => 'many2one',
                'foreign_object'    => 'identity\Identity',
                'description'       => "The organization the user relates to (defaults to current).",
                'default'           => 1
            ],

            'organisation_id' => [
                'type'              => 'many2one',
                'foreign_object'    => 'identity\Organisation',
                'description'       => 'The organisation the user belongs to.',
                'default'           => 1
            ],

            'role_assignments_ids' => [
                'type'              => 'one2many',
                'foreign_object'    => 'hr\role\RoleAssignment',
                'foreign_field'     => 'user_id',
                'description'       => 'Roles assigned to the user.'
            ],

            'employee_id' => [
                'type'              => 'computed',
                'result_type'       => 'many2one',
                'foreign_object'    => 'hr\employee\Employee',
                'store'             => true,
                'relation'          => ['identity_id' => 'employee_id'],
                'description'       => 'The employee relating to the user, if set.',
            ]

        ];
    }

    public static function getActions() {
        return [
            'sync_from_identity' => [
                'description'   => 'Force sync values from related identity.',
                'function'      => 'doSyncFromIdentity'
            ],

            'sync_uuid_links' => [
                'description'   => 'Synchronize the uuid links.',
                'policies'      => [],
                'function'      => 'doSyncUuidLinks'
            ]
        ];
    }

    public static function oncreate($self, $values, $orm = null) {
        foreach($self as $id => $user) {
            if(constant('FMT_INSTANCE_TYPE') === 'global') {
                do {
                    $uuid = DataGenerator::uuid();
                    $existing = $orm->search(static::class, ['uuid', '=', $uuid]);
                } while( $existing > 0 && count($existing) > 0 );

                self::id($id)->update(['uuid' => $uuid]);
            }
        }
        parent::oncreate($self, $values);
    }

    protected static function onupdateInstanceUuid($self) {
        $self->read(['instance_uuid']);
        foreach($self as $id => $user) {
            if($user['instance_uuid']) {
                $instance = Instance::search(['uuid', '=', $user['instance_uuid']])->first();
                if($instance) {
                    self::id($id)->update(['instance_id' => $id]);
                }
            }
        }
    }

    protected static function onupdateIdentityId($self) {
        $self->read(['identity_id']);
        foreach($self as $id => $user) {
            if($user['identity_id']) {
                Identity::id($user['identity_id'])->update(['user_id' => $id]);
            }
        }
    }

    protected static function doSyncFromIdentity($self, $orm) {
        static $common_fields = [
                'firstname',
                'lastname',
            ];

        $self->read(['identity_id']);
        foreach($self as $id => $identity) {
            if(!$identity['identity_id']) {
                continue;
            }

            $orm_events = $orm->disableEvents();

            $parentIdentity = Identity::id($identity['identity_id'])
                ->read($common_fields)
                ->first(true);

            if(!$parentIdentity) {
                continue;
            }

            $values = [];
            foreach($common_fields as $field) {
                if(array_key_exists($field, $parentIdentity)) {
                    $values[$field] = $parentIdentity[$field];
                }
            }
            self::id($id)->update($values);

            $orm->enableEvents($orm_events);
        }

    }

    protected static function doSyncUuidLinks($self) {
        $self->read(['identity_id', 'identity_uuid']);
        foreach($self as $id => $user) {
            if(!empty($user['identity_uuid'])) {
                $identity = Identity::search(['uuid', '=', $user['identity_uuid']])
                    ->first();

                if($identity && $identity['identity_id'] !== $identity['id']) {
                    self::id($id)->update(['identity_id' => $identity['id']]);
                }
            }
        }
    }
}
