<?php
/*
    Developed by Yesbabylon - https://yesbabylon.com
    (c) 2025-2026 Yesbabylon SA
    Licensed under the GNU AGPL v3 License - https://www.gnu.org/licenses/agpl-3.0.html
*/
namespace identity;

use equal\data\DataGenerator;
use infra\quota\Quota;
use infra\server\Instance;
use realestate\ownership\Owner;

class User extends \core\User {

    public static function getName() {
        return 'User';
    }

    public static function constants() {
        return ['AUTH_SECRET_KEY', 'FMT_INSTANCE_TYPE'];
    }

    public static function getColumns() {
        return [

            'name' => [
                'type'              => 'computed',
                'result_type'       => 'string',
                'description'       => "The name of the User.",
                'relation'          => ['identity_id' => 'name'],
                'store'             => true,
                'readonly'          => true
            ],

            'login' => [
                'type'              => 'string',
                'usage'             => 'email',
                'required'          => true,
                // 'unique'            => true,
                'dependents'        => ['name']
            ],

            'uuid' => [
                'type'              => 'string',
                'usage'             => 'text/plain:36',
                // #memo - commented for testing because items are on the same instance
                // #todo - uncomment for PROD
                // 'unique'            => true,
                'description'       => 'Unique identifier from the Master instance.'
            ],

            'validated' => [
                'type'              => 'boolean',
                'default'           => false,
                'description'       => 'Flag telling if the User account has been validated.',
                'help'              => "This fields is used at auth & signin to prevent non-validated user to log in.",
                'onupdate'          => 'onupdateValidated'
            ],

            /*
                Following `source_*` fields apply to imported protected entities.
            */

            'source' => [
                'type'              => 'string',
                'description'       => 'The source the Identity originated from.',
                'selection'         => [
                    'manual',           // manual creation
                    'internal',         // identity generated by the software (imported, sync, ...)
                    'external'          // identity retrieved from an external source (API, ...)
                ],
                'default'           => 'manual'
            ],

            'source_type' => [
                'type'              => 'string',
                'selection'         => [
                    'eid',
                    'iam_auth',
                    'registry',
                    'third_party',
                    'manual'
                ],
                'default'           => 'manual',
                'description'       => 'Type of source (eid, registry, manual, etc.)',
                'help'              => 'Indicates how the identity data was obtained. In case of manual encoding, there is no proof for that value.',
            ],

            'source_origin' => [
                'type'              => 'string',
                'description'       => 'Detailed origin of the source (e.g. BCE, itsme, employer).',
                'help'              => 'Specifies the originating system, registry or third party.',
            ],

            'source_date' => [
                'type'              => 'datetime',
                'description'       => 'Date when the identity information was collected or encoded.',
                'help'              => 'Used to assess the freshness of the information.',
            ],

            'source_verification_status' => [
                'type'              => 'string',
                'selection'         => [
                    'pending',
                    'rejected',
                    'conflict',
                    'verified',
                ],
                'default'           => 'pending',
                'description'       => 'Status of the verification of the source (validity of the data).',
            ],

            'instance_id' => [
                'type'              => 'many2one',
                'foreign_object'    => 'infra\server\Instance',
                'description'       => 'Instance the object relates to (origin).',
                'dependents'        => ['instance_uuid']
            ],

            'instance_uuid' => [
                'type'              => 'computed',
                'result_type'       => 'string',
                'store'             => true,
                'instant'           => true,
                'relation'          => ['instance_id' => 'uuid'],
                'onupdate'          => 'onupdateInstanceUuid',
                'description'       => 'UUID of the origin instance the object comes from.'
            ],

            'identity_id' => [
                'type'              => 'many2one',
                'foreign_object'    => 'identity\Identity',
                'domain'            => ['type', '=', 'IN'],
                'description'       => 'The identity the user relates to.',
                'help'              => 'The identity that this user relates to on the current instance. If set, the user details (name, email, etc.) will be synchronized from the identity.',  
                'onupdate'          => 'onupdateIdentityId',
                'dependents'        => ['name', 'employee_id', 'identity_uuid']
            ],

            'identity_uuid' => [
                'type'              => 'computed',
                'result_type'       => 'string',
                'store'             => true,
                'instant'           => true,
                'relation'          => ['identity_id' => 'uuid'],
                'description'       => 'Identity the object relates to.',
            ],

            'setting_values_ids' => [
                'type'              => 'one2many',
                'foreign_object'    => 'fmt\setting\SettingValue',
                'foreign_field'     => 'user_id',
                'description'       => 'List of settings that relate to the user.'
            ],

            'owner_identity_id' => [
                'type'              => 'many2one',
                'foreign_object'    => 'identity\Identity',
                'description'       => "The organization the user relates to (defaults to current).",
                'default'           => 1
            ],

            'organisation_id' => [
                'type'              => 'many2one',
                'foreign_object'    => 'identity\Organisation',
                'description'       => 'The organisation the user belongs to.',
                'default'           => 1
            ],

            'role_assignments_ids' => [
                'type'              => 'one2many',
                'foreign_object'    => 'hr\role\RoleAssignment',
                'foreign_field'     => 'user_id',
                'description'       => 'Roles assigned to the user.'
            ],

            'employee_id' => [
                'type'              => 'computed',
                'result_type'       => 'many2one',
                'foreign_object'    => 'hr\employee\Employee',
                'store'             => true,
                'readonly'          => true,
                'relation'          => ['identity_id' => 'employee_id'],
                'description'       => 'The employee relating to the user, if set.',
            ],

            'is_system' => [
                'type'              => 'boolean',
                'default'           => false,
                'readonly'          => false,
                'description'       => 'The user is related to system administration.',
                'help'              => 'The user has system-administration purpose and must not be shown to business-users.'
            ],

            'is_employee' => [
                'type'              => 'computed',
                'result_type'       => 'boolean',
                'function'          => 'calcIsEmployee',
                'store'             => true,
                'readonly'          => true,
                'onupdate'          => 'onupdateIsEmployee'
            ],

            'is_owner' => [
                'type'              => 'computed',
                'result_type'       => 'boolean',
                'function'          => 'calcIsOwner',
                'store'             => true,
                'readonly'          => true,
                'onupdate'          => 'onupdateIsOwner'
            ]

        ];
    }

    public function getUnique(): array {
        return [
            ['login', 'instance_uuid']
        ];
    }

    public static function getActions() {
        return [
            'sync_from_identity' => [
                'description'   => 'Force sync values from related identity.',
                'function'      => 'doSyncFromIdentity'
            ],

            'sync_uuid_links' => [
                'description'   => 'Synchronize the uuid links.',
                'policies'      => [],
                'function'      => 'doSyncUuidLinks'
            ]
        ];
    }

    protected static function calcIsEmployee($self) {
        $result = [];
        $self->read(['employee_id']);
        foreach($self as $id => $user) {
            $result[$id] = (bool) $user['employee_id'];
        }
        return $result;
    }

    /**
     * There are two approaches to check this:
     * either through specific assignments;
     * or through the identity.
     *
     * Assignments are in principle intended for employees, so we prefer to use identities.
     */
    protected static function calcIsOwner($self) {
        $result = [];
        $self->read(['identity_id']);
        foreach($self as $id => $user) {
            $result[$id] = false;
            $owners = Owner::search(['identity_id', '=', $user['identity_id']])->ids();
            if(count($owners)) {
                $result[$id] = true;
            }
            /*
            foreach($user['role_assignments_ids'] as $role_assignment) {
                if($role_assignment['role_code'] === 'owner') {
                    $result[$id] = true;
                    break;
                }
            }
            */
        }
        return $result;
    }

    public static function cancreate($self, $values): array {
        $quota = Quota::search([
            ['code', '=', 'auth.users.count'],
            ['is_active', '=', true]
        ])
            ->do('check-thresholds')
            ->read(['is_reached'])
            ->first();

        if($quota && $quota['is_reached']) {
            if((isset($values['employee_id']) && $values['employee_id']) || (isset($values['owner_id']) && $values['owner_id']) || (isset($values['validated']) && $values['validated'])) {
                return ['quota' => ['quota_reached' => 'The quota for non-system user creation has been reached.']];
            }
        }

        return [];
    }

    public static function oncreate($self, $values, $orm = null) {
        foreach($self as $id => $user) {
            if(constant('FMT_INSTANCE_TYPE') === 'global') {
                do {
                    $uuid = DataGenerator::uuid();
                    $existing = $orm->search(static::class, ['uuid', '=', $uuid]);
                } while( $existing > 0 && count($existing) > 0 );

                self::id($id)->update(['uuid' => $uuid]);
            }
            elseif(constant('FMT_INSTANCE_TYPE') === 'agency') {
                #memo - only one instance (itself) on agency instance
                $instance = Instance::search()->first();

                if($instance) {
                    self::id($id)->update(['instance_id' => $instance['id']]);
                }
            }
        }
        parent::oncreate($self, $values);
    }

    public static function canupdate($self, $values): array {
        $quota = Quota::search([
            ['code', '=', 'auth.users.count'],
            ['is_active', '=', true]
        ])
            ->do('check-thresholds')
            ->read(['is_reached'])
            ->first();

        if($quota && $quota['is_reached']) {
            if((isset($values['employee_id']) && $values['employee_id']) || (isset($values['owner_id']) && $values['owner_id']) || (isset($values['validated']) && $values['validated'])) {
                return ['quota' => ['quota_reached' => 'The quota for non-system user creation has been reached.']];
            }
        }

        return [];
    }

    public static function onupdateValidated($self): void {
        Quota::search([
            ['code', '=', 'auth.users.count'],
            ['is_active', '=', true]
        ])
            ->do('check-thresholds');
    }

    public static function onupdateIsEmployee($self): void {
        Quota::search([
            ['code', '=', 'auth.users.count'],
            ['is_active', '=', true]
        ])
            ->do('check-thresholds');
    }

    public static function onupdateIsOwner($self): void {
        Quota::search([
            ['code', '=', 'auth.users.count'],
            ['is_active', '=', true]
        ])
            ->do('check-thresholds');

    }

    protected static function onupdateInstanceUuid($self) {
        $self->read(['instance_uuid']);
        foreach($self as $id => $user) {
            if($user['instance_uuid']) {
                $instance = Instance::search(['uuid', '=', $user['instance_uuid']])->first();
                if($instance) {
                    self::id($id)->update(['instance_id' => $id]);
                }
            }
        }
    }

    protected static function onupdateIdentityId($self) {
        $self->read(['identity_id']);
        foreach($self as $id => $user) {
            if($user['identity_id']) {
                Identity::id($user['identity_id'])->update(['user_id' => $id]);
            }
        }
    }

    protected static function doSyncFromIdentity($self, $orm) {
        static $common_fields = [
                'firstname',
                'lastname',
            ];

        $self->read(['identity_id']);
        foreach($self as $id => $identity) {
            if(!$identity['identity_id']) {
                continue;
            }

            $orm_events = $orm->disableEvents();

            $parentIdentity = Identity::id($identity['identity_id'])
                ->read($common_fields)
                ->first(true);

            if(!$parentIdentity) {
                continue;
            }

            $values = [];
            foreach($common_fields as $field) {
                if(array_key_exists($field, $parentIdentity)) {
                    $values[$field] = $parentIdentity[$field];
                }
            }
            self::id($id)->update($values);

            $orm->enableEvents($orm_events);
        }

    }

    protected static function doSyncUuidLinks($self) {
        $self->read(['identity_id', 'identity_uuid', 'instance_id', 'instance_uuid']);
        foreach($self as $id => $user) {
            // identity
            if(!empty($user['identity_uuid'])) {
                $identity = Identity::search(['uuid', '=', $user['identity_uuid']])
                    ->first();

                if($identity && $user['identity_id'] !== $identity['id']) {
                    self::id($id)->update(['identity_id' => $identity['id']]);
                }
            }

            // instance
            if(!empty($user['instance_uuid'])) {
                $instance = Instance::search(['uuid', '=', $user['instance_uuid']])
                    ->first();

                if($instance && $user['instance_id'] !== $instance['id']) {
                    self::id($id)->update(['instance_id' => $instance['id']]);
                }
            }
        }
    }
}
