<?php
/*
    Developed by Yesbabylon - https://yesbabylon.com
    (c) 2025-2026 Yesbabylon SA
    Licensed under the GNU AGPL v3 License - https://www.gnu.org/licenses/agpl-3.0.html
*/

use finance\accounting\AccountingEntryLine;
use finance\accounting\Matching;
use finance\bank\BankStatementLine;
use realestate\sale\pay\Funding;
use realestate\sale\pay\Payment;

[$params, $providers] = eQual::announce([
    'description'   => 'Match a given series of accounting entry lines and match them with given pending Bank Statement Line.',
    'help'          => "This controller creates a partial Matching (`matching_level` = `part`) and attach it to the Bank Statement Line.
        Upon validation of the BankStatementLine, the generated AccountingEntryLines will be linked to that Matching.
        Note: When linking a bank statement line, its Accounting Entry Line do exist yet.",
    'params'        => [
        'id' =>  [
            'type'              => 'many2one',
            'foreign_object'    => 'finance\bank\BankStatementLine',
            'required'          => true
        ],
        'selected_ids' => [
            'description'       => 'List of unique identifiers of Accounting Entry lines to be linked to the statement line.',
            'type'              => 'array',
            'required'          => true
        ]
    ],
    'response'      => [
        'content-type'  => 'application/json',
        'charset'       => 'utf-8',
        'accept-origin' => '*'
    ],
    'providers'     => [ 'context', 'orm' ]
]);
/**
 * @var \equal\php\Context $context
 * @var \equal\orm\ObjectManager $orm
 */
['context' => $context, 'orm' => $orm] = $providers;


$result = [];


// #todo - check consistency (has been done in UI)

$bankStatementLine = BankStatementLine::id($params['id'])
    ->read([
        'condo_id',
        'status',
        'amount',
        'communication',
        'date',
        'accounting_account_id',
        'bank_statement_id' => ['bank_account_id']
    ])
    ->first();

if(!$bankStatementLine) {
    throw new Exception('unknown_bank_statement_line', EQ_ERROR_UNKNOWN_OBJECT);
}

if($bankStatementLine['status'] !== 'pending') {
    throw new Exception('posted_bank_statement_line', EQ_ERROR_INVALID_PARAM);
}

if(!isset($bankStatementLine['condo_id'])) {
    throw new Exception('missing_bank_statement_line_condo', EQ_ERROR_INVALID_PARAM);
}

if(!isset($bankStatementLine['accounting_account_id'])) {
    throw new Exception('missing_bank_statement_line_account', EQ_ERROR_INVALID_PARAM);
}

$accountingEntryLines = AccountingEntryLine::ids($params['selected_ids'])
    ->read([
        'matching_id',
        'funding_id',
        'debit',
        'credit'
    ]);

if($accountingEntryLines->count() <= 0) {
    throw new Exception('invalid_empty_selection', EQ_ERROR_INVALID_PARAM);
}


/*
We know that the entry generated by the line will be balanced with the selected entry lines
(if the amount is negative, it will be posted to the debit, otherwise to the credit)

We need to:
    - detach all lines from their existing matching (with cascading events)
    - create a new matching
    - attach the lines to the new matching
*/

$map_matchings_ids = [];
// compute accounting amount (scope of matching)
$accounting_amount = 0.0;


foreach($accountingEntryLines as $accounting_entry_line_id => $accountingEntryLine) {
    $accounting_amount += ($accountingEntryLine['debit'] - $accountingEntryLine['credit']);

    if(!$accountingEntryLine['matching_id']) {
        continue;
    }

    $map_matchings_ids[$accountingEntryLine['matching_id']] = true;
}



$events = $orm->disableEvents();

// 1) create a new Matching

$matching = Matching::create([
        'condo_id'              => $bankStatementLine['condo_id'],
        'accounting_account_id' => $bankStatementLine['accounting_account_id']
    ])
    ->first();

// link accounting entry lines
$accountingEntryLines->update([
    'matching_id' => $matching['id']
]);

// link bank statement line
BankStatementLine::id($bankStatementLine['id'])->update([
    'matching_id' => $matching['id']
]);

$orm->enableEvents($events);

Payment::search([
        ['bank_statement_line_id', '=', $bankStatementLine['id']],
        ['proforma', '=', 'proforma']
    ])
    ->delete(true);

// 2) Allocation to fundings

// effective amount to allocate
$remaining_amount = $accounting_amount;

// retrieve related fundings
$fundings = Funding::search([
        ['condo_id', '=', $bankStatementLine['condo_id']],
        ['accounting_account_id', '=', $bankStatementLine['accounting_account_id']],
        ['status', '<>', 'balanced'],
        ['funding_type', '<>', 'due_balance'],
    ], ['sort' => ['issue_date' => 'asc']])
    ->read(['id', 'remaining_amount'])
    ->get();


// allocate payments (FIFO)
foreach($fundings as $funding) {

    if(abs($remaining_amount) < 0.01) {
        break;
    }

    $allocatable = min(abs($funding['remaining_amount']), abs($remaining_amount));

    // sign follows the funding (consumer)
    $allocated = ($funding['remaining_amount'] > 0 ? 1 : -1) * $allocatable;

    // prevent overshoot
    if(abs($remaining_amount - $allocated) > abs($remaining_amount)) {
        continue;
    }

    // #memo - Payment are 'posted' upon validation of the BankStatementLine
    Payment::create([
        'condo_id'                => $bankStatementLine['condo_id'],
        'amount'                  => $allocated,
        'communication'           => $bankStatementLine['communication'],
        'receipt_date'            => $bankStatementLine['date'],
        'receipt_bank_account_id' => $bankStatementLine['bank_statement_id']['bank_account_id'],
        'payment_origin'          => 'bank',
        'payment_method'          => 'wire_transfer',
        'bank_statement_line_id'  => $bankStatementLine['id'],
        'funding_id'              => $funding['id'],
    ]);

    $remaining_amount -= $allocated;
}


// 3) refresh lines & impacted matchings

if(count($map_matchings_ids)) {
    Matching::ids(array_keys($map_matchings_ids))
        ->do('refresh_matching_level');
}

// refresh current lines
$accountingEntryLines->do('refresh_matching_level');

BankStatementLine::id($bankStatementLine['id'])->update(['is_reconciled' => null]);

$context->httpResponse()
        ->status(204)
        ->send();
