<?php
/*
    Developed by Yesbabylon – https://yesbabylon.com
    (c) 2025–2026 Yesbabylon SA
    Licensed under the GNU AGPL v3 License – https://www.gnu.org/licenses/agpl-3.0.html
*/

use finance\accounting\AccountingEntryLine;
use finance\accounting\Matching;
use finance\bank\BankStatementLine;
use sale\pay\Payment;

[$params, $providers] = eQual::announce([
    'description'   => 'Match a given series of accounting entry lines and attach the Bank statement line to it.',
    'help'          => 'When linking a bank statement line, the accounting entry line does exist yet.',
    'params'        => [
        'id' =>  [
            'type'              => 'many2one',
            'foreign_object'    => 'finance\bank\BankStatementLine',
            'required'          => true
        ],
        'selected_ids' => [
            'description'       => 'List of unique identifiers of the objects to read.',
            'type'              => 'array',
            'required'          => true
        ]
    ],
    'response'      => [
        'content-type'  => 'application/json',
        'charset'       => 'utf-8',
        'accept-origin' => '*'
    ],
    'providers'     => [ 'context', 'orm' ]
]);
/**
 * @var \equal\php\Context $context
 * @var \equal\orm\ObjectManager $orm
 */
['context' => $context, 'orm' => $orm] = $providers;


$result = [];


// #odo - check consistency (has been done in UI)

$bankStatementLine = BankStatementLine::id($params['id'])
    ->read([
        'condo_id',
        'status',
        'accounting_account_id',
        'payments_ids'
    ])
    ->first();

if(!$bankStatementLine) {
    throw new Exception('unknown_bank_statement_line', EQ_ERROR_UNKNOWN_OBJECT);
}

if($bankStatementLine['status'] !== 'pending') {
    throw new Exception('posted_bank_statement_line', EQ_ERROR_INVALID_PARAM);
}

if(!isset($bankStatementLine['condo_id'])) {
    throw new Exception('missing_bank_statement_line_condo', EQ_ERROR_INVALID_PARAM);
}

if(!isset($bankStatementLine['accounting_account_id'])) {
    throw new Exception('missing_bank_statement_line_account', EQ_ERROR_INVALID_PARAM);
}

$accountingEntryLines = AccountingEntryLine::ids($params['selected_ids'])
    ->read([
        'matching_id',
        'funding_id'
    ]);

if($accountingEntryLines->count() <= 0) {
    throw new Exception('invalid_empty_selection', EQ_ERROR_INVALID_PARAM);
}


/*
We know that the entry generated by the line will be balanced with the selected entry lines
(if the amount is negative, it will be posted to the debit, otherwise to the credit)

We need to:
    - detach all lines from their existing matching (with cascading events)
    - create a new matching
    - attach the lines to the new matching
*/

$map_matchings_ids = [];

foreach($accountingEntryLines as $accounting_entry_line_id => $accountingEntryLine) {
    if(!$accountingEntryLine['matching_id']) {
        continue;
    }
    $map_matchings_ids[$accountingEntryLine['matching_id']] = true;
}

$found = false;

// special case: a single accounting entry line with a funding_id
if($accountingEntryLines->count() === 1) {
    $accountingEntryLine = $accountingEntryLines->first();
    if($accountingEntryLine['funding_id']) {
        $found = true;
        Payment::ids($bankStatementLine['payments_ids'])->delete(true);
        BankStatementLine::id($bankStatementLine['id'])
            ->do('reconcile_with_funding', ['funding_id' => $accountingEntryLine['funding_id']])
            ->update(['is_reconciled' => null]);
    }
}

if(!$found) {
    $events = $orm->disableEvents();

    // 1) create a new Matching

    $matching = Matching::create([
            'condo_id'              => $bankStatementLine['condo_id'],
            'accounting_account_id' => $bankStatementLine['accounting_account_id']
        ])
        ->first();

    $accountingEntryLines->update(['matching_id' => $matching['id']]);
    BankStatementLine::id($bankStatementLine['id'])->update(['matching_id' => $matching['id']]);

    $orm->enableEvents($events);

    // 2) refresh lines & impacted matchings

    if(count($map_matchings_ids)) {
        // #memo - this will cascade-update accounting entry lines still linked to theses matchings
        Matching::ids(array_keys($map_matchings_ids))->do('refresh_matching_level');
    }

    // This should result in a non-balanced state, but consistent with given selection (the accounting entry line from the bank statement line is still missing)
    $accountingEntryLines->do('refresh_matching_level');
}

$context->httpResponse()
        ->status(204)
        ->send();
