<?php

use finance\bank\Bank;
use identity\Identity;

['orm' => $orm] = eQual::inject(['orm']);

$identities_json = <<<'JSON'
[
    {
        "id": 500,
        "type_id": 3,
        "legal_name": "ABN AMRO BANK",
        "short_name": "ABN AMRO BANK",
        "has_vat": true,
        "vat_number": "BE0819210332",
        "registration_number": "0819210332",
        "nationality": "BE",
        "address_street": "Borsbeeksebrug, 30",
        "address_city": "Berchem",
        "address_zip": "2600",
        "address_country": "BE",
        "email": "commercial.banking@be.abnamro.com",
        "phone": "+3232220333",
        "bank_account_bic": "ABNABE2A",
        "is_active": true
    },
    {
        "id": 501,
        "type_id": 3,
        "legal_name": "ARGENTA BVG",
        "short_name": "ARGENTA",
        "has_vat": true,
        "vat_number": "BE0475525276",
        "registration_number": "0475525276",
        "nationality": "BE",
        "address_street": "Belgiëlei, 49-53",
        "address_city": "Anvers",
        "address_zip": "2018",
        "address_country": "BE",
        "email": "info@argenta.be",
        "phone": "+3232855111",
        "bank_account_bic": "ARSPBE22",
        "is_active": true
    },
    {
        "id": 502,
        "type_id": 3,
        "legal_name": "ATTIJARIWAFA BANK EUROPE",
        "short_name": "ATTIJARIWAFA BANK EU",
        "has_vat": true,
        "vat_number": "BE0884276150",
        "registration_number": "0884276150",
        "nationality": "BE",
        "address_street": "Boulevard Maurice Lemonnier, 128",
        "address_city": "Bruxelles",
        "address_zip": "1000",
        "address_country": "BE",
        "phone": "+3278151154",
        "bank_account_bic": "WAFABEBB",
        "is_active": true
    },
    {
        "id": 503,
        "type_id": 3,
        "legal_name": "AXA BANQUE - CRELAN",
        "short_name": "AXA BANQUE - CRELAN",
        "has_vat": true,
        "vat_number": "BE0404476835",
        "registration_number": "0404476835",
        "nationality": "BE",
        "address_street": "Boulevard Sylvain Dupuis, 251",
        "address_city": "Anderlecht",
        "address_zip": "1070",
        "address_country": "BE",
        "email": "info@crelan.be",
        "phone": "+3225587111",
        "bank_account_bic": "AXABBE22",
        "is_active": true
    },
    {
        "id": 504,
        "type_id": 3,
        "legal_name": "BBVA - BANCO BILBAO VIZCAYA ARGENTARIA",
        "short_name": "BBVA - BANCO BILBAO",
        "has_vat": true,
        "vat_number": "BE0445048470",
        "registration_number": "0445048470",
        "nationality": "BE",
        "address_street": "Cantersteen, 47",
        "address_city": "Bruxelles",
        "address_zip": "1000",
        "address_country": "BE",
        "email": "corporate.be@bbva.com",
        "phone": "+3222291801",
        "bank_account_bic": "BBVABEBB",
        "is_active": true
    },
    {
        "id": 505,
        "type_id": 3,
        "legal_name": "BANK J.VAN BREDA & C°",
        "short_name": "BANK J. VAN BREDA",
        "has_vat": true,
        "vat_number": "BE0404055577",
        "registration_number": "0404055577",
        "nationality": "BE",
        "address_street": "Ledeganckkaai, 7",
        "address_city": "Anvers",
        "address_zip": "2000",
        "address_country": "BE",
        "email": "info@banquevanbreda.be",
        "phone": "+3232450045",
        "bank_account_bic": "JVBABE22",
        "is_active": true
    },
    {
        "id": 506,
        "type_id": 3,
        "legal_name": "BANKB",
        "short_name": "BANKB",
        "has_vat": true,
        "vat_number": "BE0400040965",
        "registration_number": "0400040965",
        "nationality": "BE",
        "address_street": "Mannebeekstraat, 33",
        "address_city": "Waregem",
        "address_zip": "8790",
        "address_country": "BE",
        "email": "info@bankb.be",
        "phone": "+3256629281",
        "bank_account_bic": "CEKVBE88",
        "is_active": true
    },
    {
        "id": 507,
        "type_id": 3,
        "legal_name": "BANQUE CPH",
        "short_name": "CPH",
        "has_vat": true,
        "vat_number": "BE0402487939",
        "registration_number": "0402487939",
        "nationality": "BE",
        "address_street": "Rue Perdue, 7",
        "address_city": "Tournai",
        "address_zip": "7500",
        "address_country": "BE",
        "email": "info@cph.be",
        "phone": "+3269881411",
        "bank_account_bic": "CPHBBE75",
        "is_active": true
    },
    {
        "id": 508,
        "type_id": 3,
        "legal_name": "BANK OF AMERICA EUROPE DAC",
        "short_name": "BANK OF AMERICA",
        "has_vat": true,
        "vat_number": "BE0649796367",
        "registration_number": "0649796367",
        "nationality": "BE",
        "address_street": "Rue Belliard, 15 bte 17",
        "address_city": "Etterbeek",
        "address_zip": "1040",
        "address_country": "BE",
        "phone": "+3224018741",
        "bank_account_bic": "BOFABE3X",
        "is_active": true
    },
    {
        "id": 509,
        "type_id": 3,
        "legal_name": "BANK OF CHINA",
        "short_name": "BANK OF CHINA",
        "has_vat": true,
        "vat_number": "BE0827624586",
        "registration_number": "0827624586",
        "nationality": "BE",
        "address_street": "Boulevard du Régent, 35",
        "address_city": "Bruxelles",
        "address_zip": "1000",
        "address_country": "BE",
        "email": "service.be@bankofchina.com",
        "phone": "+3224056688",
        "bank_account_bic": "BKCHBEBB",
        "is_active": true
    },
    {
        "id": 510,
        "type_id": 3,
        "legal_name": "BANQUE DE LUXEMBOURG",
        "short_name": "BANQUE DE LUXEMBOURG",
        "has_vat": true,
        "vat_number": "BE0830227057",
        "registration_number": "0830227057",
        "nationality": "BE",
        "address_street": "Chaussée de la Hulpe, 120",
        "address_city": "Bruxelles",
        "address_zip": "1000",
        "address_country": "BE",
        "phone": "+3226634540",
        "bank_account_bic": "BLUXBE41",
        "is_active": true
    },
    {
        "id": 511,
        "type_id": 3,
        "legal_name": "BANQUE DEGROOF PETERCAM",
        "short_name": "DEGROOF PETERCAM",
        "has_vat": true,
        "vat_number": "BE0403212172",
        "registration_number": "0403212172",
        "nationality": "BE",
        "address_street": "Rue de l'Industrie, 44",
        "address_city": "Etterbeek",
        "address_zip": "1040",
        "address_country": "BE",
        "email": "contact@degroofpetercam.com",
        "phone": "+3222879111",
        "bank_account_bic": "DEGRBEBB",
        "is_active": true
    },
    {
        "id": 512,
        "type_id": 3,
        "legal_name": "BANQUE ENI",
        "short_name": "BANQUE ENI",
        "has_vat": true,
        "vat_number": "BE0879995183",
        "registration_number": "0879995183",
        "nationality": "BE",
        "address_street": "Rue Guimard, 1A",
        "address_city": "Etterbeek",
        "address_zip": "1040",
        "address_country": "BE",
        "email": "banqueeni.info@eni.com",
        "phone": "+3225511970",
        "bank_account_bic": "ENIBBEBB",
        "is_active": true
    },
    {
        "id": 513,
        "type_id": 3,
        "legal_name": "BANQUE NAGELMACKERS",
        "short_name": "NAGELMACKERS",
        "has_vat": true,
        "vat_number": "BE0404140107",
        "registration_number": "0404140107",
        "nationality": "BE",
        "address_street": "Rue Montoyer, 14",
        "address_city": "Bruxelles",
        "address_zip": "1000",
        "address_country": "BE",
        "phone": "+3222297600",
        "bank_account_bic": "BNAGBEBB",
        "is_active": true
    },
    {
        "id": 514,
        "type_id": 3,
        "legal_name": "BANQUE TRANSATLANTIQUE BELGIUM - BTB - CIC",
        "short_name": "BTB - CIC",
        "has_vat": true,
        "vat_number": "BE0872743345",
        "registration_number": "0872743345",
        "nationality": "BE",
        "address_street": "Rue De Crayer, 9",
        "address_city": "Bruxelles",
        "address_zip": "1000",
        "address_country": "BE",
        "email": "btb@banquetransatlantique.be",
        "phone": "+3226260270",
        "bank_account_bic": "CMCIBEB1",
        "is_active": true
    },
    {
        "id": 515,
        "type_id": 3,
        "legal_name": "BARCLAYS BANK IRELAND",
        "short_name": "BARCLAYS BANK",
        "has_vat": true,
        "vat_number": "BE0727958472",
        "registration_number": "0727958472",
        "nationality": "BE",
        "address_street": "Bastion Tower, Place du Champ de Mars, 5",
        "address_city": "Ixelles",
        "address_zip": "1050",
        "address_country": "BE",
        "bank_account_bic": "BARCBEBB",
        "is_active": true
    },
    {
        "id": 516,
        "type_id": 3,
        "legal_name": "BELFIUS BANQUE",
        "short_name": "BELFIUS",
        "has_vat": true,
        "vat_number": "BE0403201185",
        "registration_number": "0403201185",
        "nationality": "BE",
        "address_street": "Place Charles Rogier, 11",
        "address_city": "Saint-Josse-ten-Noode",
        "address_zip": "1210",
        "address_country": "BE",
        "email": "info@belfius.be",
        "phone": "+3222221111",
        "bank_account_bic": "GKCCBEBB",
        "is_active": true
    },
    {
        "id": 517,
        "type_id": 3,
        "legal_name": "BEOBANK",
        "short_name": "BEOBANK",
        "has_vat": true,
        "vat_number": "BE0401517147",
        "registration_number": "0401517147",
        "nationality": "BE",
        "address_street": "Boulevard du Roi Albert II, 2",
        "address_city": "Etterbeek",
        "address_zip": "1040",
        "address_country": "BE",
        "email": "info@beobank.be",
        "phone": "+3226222000",
        "bank_account_bic": "CTBKBEBX",
        "is_active": true
    },
    {
        "id": 518,
        "type_id": 3,
        "legal_name": "BNP PARIBAS FORTIS",
        "short_name": "BNP PARIBAS FORTIS - FINTRO",
        "has_vat": true,
        "vat_number": "BE0403199702",
        "registration_number": "0403199702",
        "nationality": "BE",
        "address_street": "Rue Montagne du Parc, 3",
        "address_city": "Bruxelles",
        "address_zip": "1000",
        "address_country": "BE",
        "email": "info@bnpparibasfortis.com",
        "phone": "+3227622000",
        "bank_account_bic": "GEBABEBB",
        "is_active": true
    },
    {
        "id": 519,
        "type_id": 3,
        "legal_name": "BYBLOS BANK EUROPE",
        "short_name": "BYBLOS BANK EU",
        "has_vat": true,
        "vat_number": "BE0415718640",
        "registration_number": "0415718640",
        "nationality": "BE",
        "address_street": "Boulevard Bischoffsheim, 1-8",
        "address_city": "Bruxelles",
        "address_zip": "1000",
        "address_country": "BE",
        "email": "information@bbe.digital",
        "phone": "+3225510020",
        "bank_account_bic": "BYBBBEBB",
        "is_active": true
    },
    {
        "id": 520,
        "type_id": 3,
        "legal_name": "CA AUTO BANK",
        "short_name": "CA AUTO BANK",
        "has_vat": true,
        "vat_number": "BE0699630712",
        "registration_number": "0699630712",
        "nationality": "BE",
        "address_street": "Avenue Hermann-Debroux, 54",
        "address_city": "Auderghem",
        "address_zip": "1160",
        "address_country": "BE",
        "email": "customercare.belux@ca-autobank.com",
        "phone": "+3253280499",
        "bank_account_bic": "AAMMBEMM",
        "is_active": true
    },
    {
        "id": 521,
        "type_id": 3,
        "legal_name": "CA INDOSUEZ WEALTH EUROPE",
        "short_name": "CA INDOSUEZ",
        "has_vat": true,
        "vat_number": "BE0534752288",
        "registration_number": "0534752288",
        "nationality": "LU",
        "address_street": "Allée Scheffer, 39",
        "address_city": "Luxembourg",
        "address_zip": "2520",
        "address_country": "LU",
        "phone": "+35224671",
        "bank_account_bic": "CVMCBEBB",
        "is_active": true
    },
    {
        "id": 522,
        "type_id": 3,
        "legal_name": "CACEIS BANK",
        "short_name": "CACEIS BANK",
        "has_vat": true,
        "vat_number": "BE0539791736",
        "registration_number": "0539791736",
        "nationality": "BE",
        "address_street": "Avenue du Port, 86 C bte 315",
        "address_city": "Bruxelles",
        "address_zip": "1000",
        "address_country": "BE",
        "phone": "+3222092600",
        "bank_account_bic": "AAFFBEFF",
        "is_active": true
    },
    {
        "id": 523,
        "type_id": 3,
        "legal_name": "CRÉDIT AGRICOLE CIB BELGIQUE",
        "short_name": "CRÉDIT AGRICOLE BE",
        "has_vat": true,
        "vat_number": "BE0457370044",
        "registration_number": "0457370044",
        "nationality": "BE",
        "address_street": "Chaussée de La Hulpe, 120",
        "address_city": "Bruxelles",
        "address_zip": "1000",
        "address_country": "BE",
        "email": "communicationseurope@ca-cib.com",
        "phone": "+3226613350",
        "bank_account_bic": "CRLYBEBB",
        "is_active": true
    },
    {
        "id": 524,
        "type_id": 3,
        "legal_name": "CBC BANQUE",
        "short_name": "CBC",
        "has_vat": true,
        "vat_number": "BE0403211380",
        "registration_number": "0403211380",
        "nationality": "BE",
        "address_street": "Avenue Albert Ier, 60",
        "address_city": "Namur",
        "address_zip": "5000",
        "address_country": "BE",
        "phone": "+3281801880",
        "bank_account_bic": "CREGBEBB",
        "is_active": true
    },
    {
        "id": 525,
        "type_id": 3,
        "legal_name": "CITIBANK EUROPE",
        "short_name": "CITIBANK",
        "has_vat": true,
        "vat_number": "BE0643865313",
        "registration_number": "0643865313",
        "nationality": "BE",
        "address_street": "Rue des Colonies, 56",
        "address_city": "Bruxelles",
        "address_zip": "1000",
        "address_country": "BE",
        "bank_account_bic": "CITIBEBX",
        "is_active": true
    },
    {
        "id": 526,
        "type_id": 3,
        "legal_name": "COMMERZBANK",
        "short_name": "COMMERZBANK",
        "has_vat": true,
        "vat_number": "BE0416444061",
        "registration_number": "0416444061",
        "nationality": "DE",
        "address_street": "Kaiserstrasse, 16",
        "address_city": "Frankfurt am Main",
        "address_zip": "60311",
        "address_country": "DE",
        "bank_account_bic": "COBABEBX",
        "is_active": true
    },
    {
        "id": 527,
        "type_id": 3,
        "legal_name": "CNH INDUSTRIAL CAPITAL EUROPE",
        "short_name": "CNH CE",
        "has_vat": true,
        "vat_number": "BE0821165475",
        "registration_number": "0821165475",
        "nationality": "BE",
        "address_street": "Rue Montagne du Parc, 8 bte 1",
        "address_city": "Bruxelles",
        "address_zip": "1000",
        "address_country": "BE",
        "email": "cnhcapitalbenelux@ivecogroup.com",
        "phone": "+3250877500",
        "bank_account_bic": "YYYYBEYY",
        "is_active": true
    },
    {
        "id": 528,
        "type_id": 3,
        "legal_name": "CRELAN",
        "short_name": "CRELAN",
        "has_vat": true,
        "vat_number": "BE0205764318",
        "registration_number": "0205764318",
        "nationality": "BE",
        "address_street": "Boulevard Sylvain Dupuis, 251",
        "address_city": "Anderlecht",
        "address_zip": "1070",
        "address_country": "BE",
        "email": "info@crelan.be",
        "phone": "+3225587111",
        "bank_account_bic": "NICABEBB",
        "is_active": true
    },
    {
        "id": 529,
        "type_id": 3,
        "legal_name": "DELEN PRIVATE BANK",
        "short_name": "DELEN PRIVATE BANK",
        "has_vat": true,
        "vat_number": "BE0453076211",
        "registration_number": "0453076211",
        "nationality": "BE",
        "address_street": "Jan Van Rijswijcklaan, 184",
        "address_city": "Anvers",
        "address_zip": "2020",
        "address_country": "BE",
        "phone": "+3232445566",
        "bank_account_bic": "GOLABEB1",
        "is_active": true
    },
    {
        "id": 530,
        "type_id": 3,
        "legal_name": "DEUTSCHE BANK AG",
        "short_name": "DEUTSCHE BANK",
        "has_vat": true,
        "vat_number": "BE0418371094",
        "registration_number": "0418371094",
        "nationality": "BE",
        "address_street": "Avenue Marnix, 13-15",
        "address_city": "Bruxelles",
        "address_zip": "1000",
        "address_country": "BE",
        "email": "info@db.com",
        "phone": "+3225516511",
        "bank_account_bic": "DEUTBEBE",
        "is_active": true
    },
    {
        "id": 531,
        "type_id": 3,
        "legal_name": "DIERICKX LEYS PRIVATE BANK",
        "short_name": "DIERICKX LEYS PRIVATE BANK",
        "has_vat": true,
        "vat_number": "BE0413564943",
        "registration_number": "0413564943",
        "nationality": "BE",
        "address_street": "Jan Van Rijswijcklaan, 184",
        "address_city": "Anvers",
        "address_zip": "2020",
        "address_country": "BE",
        "email": "antwerpen@dierickxleys.be",
        "phone": "+3232410999",
        "bank_account_bic": "DIERBE21",
        "is_active": true
    },
    {
        "id": 532,
        "type_id": 3,
        "legal_name": "EDMOND DE ROTHSCHILD EUROPE",
        "short_name": "EDMOND DE ROTHSCHILD",
        "has_vat": true,
        "vat_number": "BE0479608085",
        "registration_number": "0479608085",
        "nationality": "LU",
        "address_street": "Rue Robert Stumper, 4",
        "address_city": "Luxembourg",
        "address_zip": "2557",
        "address_country": "LU",
        "bank_account_bic": "PRIBBEBB",
        "is_active": true
    },
    {
        "id": 533,
        "type_id": 3,
        "legal_name": "EUROCLEAR BANK",
        "short_name": "EUROCLEAR",
        "has_vat": true,
        "vat_number": "BE0429875591",
        "registration_number": "0429875591",
        "nationality": "BE",
        "address_street": "Boulevard du Roi Albert II, 1",
        "address_city": "Saint-Josse-ten-Noode",
        "address_zip": "1210",
        "address_country": "BE",
        "bank_account_bic": "MGTCBEBE",
        "is_active": true
    },
    {
        "id": 534,
        "type_id": 3,
        "legal_name": "EUROPABANK",
        "short_name": "EUROPABANK",
        "has_vat": true,
        "vat_number": "BE0400028394",
        "registration_number": "0400028394",
        "nationality": "BE",
        "address_street": "Burgstraat, 170",
        "address_city": "Gand",
        "address_zip": "9000",
        "address_country": "BE",
        "email": "info@europabank.be",
        "phone": "+3292247350",
        "bank_account_bic": "EURBBE99",
        "is_active": true
    },
    {
        "id": 535,
        "type_id": 3,
        "legal_name": "HSBC CONTINENTAL EUROPE",
        "short_name": "HSBC",
        "has_vat": true,
        "vat_number": "BE0708865310",
        "registration_number": "0708865310",
        "nationality": "BE",
        "address_street": "Square de Meeûs, 23",
        "address_city": "Bruxelles",
        "address_zip": "1000",
        "address_country": "BE",
        "phone": "+3227612670",
        "bank_account_bic": "HSBCBEBB",
        "is_active": true
    },
    {
        "id": 536,
        "type_id": 3,
        "legal_name": "ING BELGIQUE",
        "short_name": "ING BELGIQUE",
        "has_vat": true,
        "vat_number": "BE0403200393",
        "registration_number": "0403200393",
        "nationality": "BE",
        "address_street": "Avenue Marnix, 24",
        "address_city": "Bruxelles",
        "address_zip": "1000",
        "address_country": "BE",
        "email": "info@ing.be",
        "phone": "+3224646001",
        "bank_account_bic": "BBRUBEBB",
        "is_active": true
    },
    {
        "id": 537,
        "type_id": 3,
        "legal_name": "J.P. MORGAN S.E.",
        "short_name": "J.P. MORGAN S.E.",
        "has_vat": true,
        "vat_number": "BE0715622844",
        "registration_number": "0715622844",
        "nationality": "BE",
        "address_street": "Boulevard du Régent, 35",
        "address_city": "Bruxelles",
        "address_zip": "1000",
        "address_country": "BE",
        "phone": "+3222088811",
        "bank_account_bic": "AAQQBEQQ",
        "is_active": true
    },
    {
        "id": 538,
        "type_id": 3,
        "legal_name": "KBC BANK",
        "short_name": "KBC",
        "has_vat": true,
        "vat_number": "BE0462920226",
        "registration_number": "0462920226",
        "nationality": "BE",
        "address_street": "Avenue du Port, 2",
        "address_city": "Molenbeek-Saint-Jean",
        "address_zip": "1080",
        "address_country": "BE",
        "phone": "+3278152154",
        "bank_account_bic": "KREDBEBB",
        "is_active": true
    },
    {
        "id": 539,
        "type_id": 3,
        "legal_name": "KEYTRADE BANK - ARKEA DIRECT BANK",
        "short_name": "KEYTRADE - ARKEA",
        "has_vat": true,
        "vat_number": "BE0879257191",
        "registration_number": "0879257191",
        "nationality": "BE",
        "address_street": "Boulevard du Souverain, 100",
        "address_city": "Watermael-Boitsfort",
        "address_zip": "1170",
        "address_country": "BE",
        "email": "info@keytradebank.be",
        "phone": "+3226799000",
        "bank_account_bic": "KEYTBEBB",
        "is_active": true
    },
    {
        "id": 540,
        "type_id": 3,
        "legal_name": "LOMBARD ODIER EUROPE",
        "short_name": "LOMBARD ODIER EUROPE",
        "has_vat": true,
        "vat_number": "BE0500864745",
        "registration_number": "0500864745",
        "nationality": "BE",
        "address_street": "Avenue Louise, 81 bte 12",
        "address_city": "Ixelles",
        "address_zip": "1050",
        "address_country": "BE",
        "phone": "+3225430830",
        "bank_account_bic": "LOCYBEBB",
        "is_active": true
    },
    {
        "id": 541,
        "type_id": 3,
        "legal_name": "MEDIRECT BANK",
        "short_name": "MEDIRECT BANK",
        "has_vat": true,
        "vat_number": "BE0553851093",
        "registration_number": "0553851093",
        "nationality": "BE",
        "address_street": "Boulevard de l'Impératrice, 66",
        "address_city": "Bruxelles",
        "address_zip": "1000",
        "address_country": "BE",
        "email": "info@medirect.be",
        "phone": "+3228872005",
        "bank_account_bic": "MBWMBEBB",
        "is_active": true
    },
    {
        "id": 542,
        "type_id": 3,
        "legal_name": "MUFG BANK EUROPE",
        "short_name": "MUFG BANK EUROPE",
        "has_vat": true,
        "vat_number": "BE0648982458",
        "registration_number": "0648982458",
        "nationality": "BE",
        "address_street": "Boulevard Louis Schmidt, 29",
        "address_city": "Etterbeek",
        "address_zip": "1040",
        "address_country": "BE",
        "phone": "+3225514411",
        "bank_account_bic": "BOTKBEBX",
        "is_active": true
    },
    {
        "id": 543,
        "type_id": 3,
        "legal_name": "NEWB",
        "short_name": "NEWB",
        "has_vat": true,
        "vat_number": "BE0836324003",
        "registration_number": "0836324003",
        "nationality": "BE",
        "address_street": "Galerie Ravenstein, 2",
        "address_city": "Bruxelles",
        "address_zip": "1000",
        "address_country": "BE",
        "email": "info@newb.coop",
        "phone": "+3224862915",
        "bank_account_bic": "NEECBEB2",
        "is_active": true
    },
    {
        "id": 544,
        "type_id": 3,
        "legal_name": "NIBC BANK",
        "short_name": "NIBC BANK",
        "has_vat": true,
        "vat_number": "BE0456775869",
        "registration_number": "0456775869",
        "nationality": "BE",
        "address_street": "Rue Royale, 71",
        "address_city": "Bruxelles",
        "address_zip": "1000",
        "address_country": "BE",
        "email": "info@nibc.be",
        "phone": "+3280063400",
        "bank_account_bic": "DNIBBE21",
        "is_active": true
    },
    {
        "id": 545,
        "type_id": 3,
        "legal_name": "PUILAETCO - QUINTET PRIVATE BANK (EUROPE)",
        "short_name": "QUINTET PRIVATE BANK",
        "has_vat": true,
        "vat_number": "BE0755503702",
        "registration_number": "0755503702",
        "nationality": "BE",
        "address_street": "Boulevard du Souverain, 25 bte 14",
        "address_city": "Watermael-Boitsfort",
        "address_zip": "1170",
        "address_country": "BE",
        "phone": "+3226794700",
        "bank_account_bic": "PUILBEBB",
        "is_active": true
    },
    {
        "id": 546,
        "type_id": 3,
        "legal_name": "RABOBANK",
        "short_name": "RABOBANK",
        "has_vat": true,
        "vat_number": "BE0426220671",
        "registration_number": "0426220671",
        "nationality": "BE",
        "address_street": "Generaal Lemanstraat, 55 bte 7",
        "address_city": "Anvers",
        "address_zip": "2018",
        "address_country": "BE",
        "email": "rabo.antwerpen.info@rabobank.com",
        "phone": "+3232892888",
        "bank_account_bic": "RABOBE22",
        "is_active": true
    },
    {
        "id": 547,
        "type_id": 3,
        "legal_name": "REVOLUT BELGIUM",
        "short_name": "REVOLUT",
        "has_vat": true,
        "vat_number": "BE0784549658",
        "registration_number": "0784549658",
        "nationality": "BE",
        "address_street": "Square de Meeûs, 35",
        "address_city": "Bruxelles",
        "address_zip": "1000",
        "address_country": "BE",
        "bank_account_bic": "REVOBEB2",
        "is_active": true
    },
    {
        "id": 548,
        "type_id": 3,
        "legal_name": "ROTHSCHILD MARTIN MAUREL",
        "short_name": "ROTHSCHILD MARTIN MAUREL",
        "has_vat": true,
        "vat_number": "BE0877996092",
        "registration_number": "0877996092",
        "nationality": "BE",
        "address_street": "Rue de la Régence, 52",
        "address_city": "Bruxelles",
        "address_zip": "1000",
        "address_country": "BE",
        "phone": "+3226277730",
        "bank_account_bic": "RCBPBEBB",
        "is_active": true
    },
    {
        "id": 549,
        "type_id": 3,
        "legal_name": "SANTANDER CONSUMER FINANCE",
        "short_name": "SANTANDER",
        "has_vat": true,
        "vat_number": "BE0763791559",
        "registration_number": "0763791559",
        "nationality": "BE",
        "address_street": "Guldensporenpark, 81",
        "address_city": "Merelbeke",
        "address_zip": "9820",
        "address_country": "BE",
        "email": "info@santanderconsumerbank.be",
        "phone": "+3225889625",
        "bank_account_bic": "BSCHBEBB",
        "is_active": true
    },
    {
        "id": 550,
        "type_id": 3,
        "legal_name": "SAXO BANK",
        "short_name": "SAXO BANK",
        "has_vat": true,
        "vat_number": "BE1003939706",
        "registration_number": "1003939706",
        "nationality": "BE",
        "address_street": "Italiëlei, 124 bte 101",
        "address_city": "Anvers",
        "address_zip": "2000",
        "address_country": "BE",
        "email": "belgie@saxobank.com",
        "phone": "+3235005222",
        "bank_account_bic": "SAXBBEB1",
        "is_active": true
    },
    {
        "id": 551,
        "type_id": 3,
        "legal_name": "SOCIÉTÉ GÉNÉRALE",
        "short_name": "SOCIÉTÉ GÉNÉRALE",
        "has_vat": true,
        "vat_number": "BE0455297412",
        "registration_number": "0455297412",
        "nationality": "BE",
        "address_street": "Avenue Louise, 149",
        "address_city": "Ixelles",
        "address_zip": "1050",
        "address_country": "BE",
        "phone": "+3225066511",
        "bank_account_bic": "SGABBEB2",
        "is_active": true
    },
    {
        "id": 552,
        "type_id": 3,
        "legal_name": "THE BANK OF NEW YORK MELLON",
        "short_name": "BNY - BANK OF NEW YORK",
        "has_vat": true,
        "vat_number": "BE0806743159",
        "registration_number": "0806743159",
        "nationality": "BE",
        "address_street": "Boulevard Anspach, 1",
        "address_city": "Bruxelles",
        "address_zip": "1000",
        "address_country": "BE",
        "phone": "+3225458111",
        "bank_account_bic": "IRVTBEBB",
        "is_active": true
    },
    {
        "id": 553,
        "type_id": 3,
        "legal_name": "TRIODOS BANK",
        "short_name": "TRIODOS",
        "has_vat": true,
        "vat_number": "BE0450507887",
        "registration_number": "0450507887",
        "nationality": "BE",
        "address_street": "Boulevard Baudouin, 31\/5",
        "address_city": "Bruxelles",
        "address_zip": "1000",
        "address_country": "BE",
        "email": "info@triodos.be",
        "phone": "+3225482820",
        "bank_account_bic": "TRIOBEBB",
        "is_active": true
    },
    {
        "id": 554,
        "type_id": 3,
        "legal_name": "UNICREDIT - AION BANK",
        "short_name": "UNICREDIT - AION BANK",
        "has_vat": true,
        "vat_number": "BE0403199306",
        "registration_number": "0403199306",
        "nationality": "BE",
        "address_street": "Square Victoria Régina, 1",
        "address_city": "Saint-Josse-ten-Noode",
        "address_zip": "1210",
        "address_country": "BE",
        "email": "info@unicredit.be",
        "bank_account_bic": "BMPBBEBB",
        "is_active": true
    },
    {
        "id": 555,
        "type_id": 3,
        "legal_name": "UNITED TAIWAN BANK",
        "short_name": "UNITED TAIWAN BANK",
        "has_vat": true,
        "vat_number": "BE0448490386",
        "registration_number": "0448490386",
        "nationality": "BE",
        "address_street": "Square de Meeûs, 1 \/ 1F",
        "address_city": "Bruxelles",
        "address_zip": "1000",
        "address_country": "BE",
        "email": "info@utb-bank.be",
        "phone": "+3222305359",
        "bank_account_bic": "UTWBBEBB",
        "is_active": true
    },
    {
        "id": 556,
        "type_id": 3,
        "legal_name": "VAN DE PUT & CO BANQUIERS PRIVÉS",
        "short_name": "VAN DE PUT & CO",
        "has_vat": true,
        "vat_number": "BE0404501381",
        "registration_number": "0404501381",
        "nationality": "BE",
        "address_street": "Van Putlei, 74-76",
        "address_city": "Anvers",
        "address_zip": "2018",
        "address_country": "BE",
        "email": "info@vandeput.be",
        "phone": "+3232309819",
        "bank_account_bic": "VAPEBE22",
        "is_active": true
    },
    {
        "id": 557,
        "type_id": 3,
        "legal_name": "MERCIER VAN LANSCHOT KEMPEN",
        "short_name": "MERCIER VAN LANSCHOT KEMPEN",
        "has_vat": true,
        "vat_number": "BE0873296641",
        "registration_number": "0873296641",
        "nationality": "BE",
        "address_street": "Desguinlei, 50",
        "address_city": "Anvers",
        "address_zip": "2018",
        "address_country": "BE",
        "email": "mvldirect@merciervanlanschot.be",
        "phone": "+3232866980",
        "bank_account_bic": "FVLBBE22",
        "is_active": true
    },
    {
        "id": 558,
        "type_id": 3,
        "legal_name": "VDK BANK",
        "short_name": "VDK BANK",
        "has_vat": true,
        "vat_number": "BE0400067788",
        "registration_number": "0400067788",
        "nationality": "BE",
        "address_street": "Keizer Karelstraat, 15",
        "address_city": "Gand",
        "address_zip": "9000",
        "address_country": "BE",
        "email": "info@vdk.be",
        "phone": "+3292673211",
        "bank_account_bic": "VDSPBE91",
        "is_active": true
    },
    {
        "id": 559,
        "type_id": 3,
        "legal_name": "WISE EUROPE",
        "short_name": "WISE EUROPE",
        "has_vat": true,
        "vat_number": "BE0713629988",
        "registration_number": "0713629988",
        "nationality": "BE",
        "address_street": "Rue du Trône, 100",
        "address_city": "Ixelles",
        "address_zip": "1050",
        "address_country": "BE",
        "bank_account_bic": "TRWIBEB1",
        "is_active": true
    }
]
JSON;

$banks_json = <<<JSON
[
    {
        "id": 500,
        "identity_id": 500,
        "supplier_type_id": 2,
        "bic": "ABNABE2A",
        "is_active": true
    },
    {
        "id": 501,
        "identity_id": 501,
        "supplier_type_id": 2,
        "bic": "ARSPBE22",
        "is_active": true
    },
    {
        "id": 502,
        "identity_id": 502,
        "supplier_type_id": 2,
        "bic": "WAFABEBB",
        "is_active": true
    },
    {
        "id": 503,
        "identity_id": 503,
        "supplier_type_id": 2,
        "bic": "AXABBE22",
        "is_active": true
    },
    {
        "id": 504,
        "identity_id": 504,
        "supplier_type_id": 2,
        "bic": "BBVABEBB",
        "is_active": true
    },
    {
        "id": 505,
        "identity_id": 505,
        "supplier_type_id": 2,
        "bic": "JVBABE22",
        "is_active": true
    },
    {
        "id": 506,
        "identity_id": 506,
        "supplier_type_id": 2,
        "bic": "CEKVBE88",
        "is_active": true
    },
    {
        "id": 507,
        "identity_id": 507,
        "supplier_type_id": 2,
        "bic": "CPHBBE75",
        "is_active": true
    },
    {
        "id": 508,
        "identity_id": 508,
        "supplier_type_id": 2,
        "bic": "BOFABE3X",
        "is_active": true
    },
    {
        "id": 509,
        "identity_id": 509,
        "supplier_type_id": 2,
        "bic": "BKCHBEBB",
        "is_active": true
    },
    {
        "id": 510,
        "identity_id": 510,
        "supplier_type_id": 2,
        "bic": "BLUXBE41",
        "is_active": true
    },
    {
        "id": 511,
        "identity_id": 511,
        "supplier_type_id": 2,
        "bic": "DEGRBEBB",
        "is_active": true
    },
    {
        "id": 512,
        "identity_id": 512,
        "supplier_type_id": 2,
        "bic": "ENIBBEBB",
        "is_active": true
    },
    {
        "id": 513,
        "identity_id": 513,
        "supplier_type_id": 2,
        "bic": "BNAGBEBB",
        "is_active": true
    },
    {
        "id": 514,
        "identity_id": 514,
        "supplier_type_id": 2,
        "bic": "CMCIBEB1",
        "is_active": true
    },
    {
        "id": 515,
        "identity_id": 515,
        "supplier_type_id": 2,
        "bic": "BARCBEBB",
        "is_active": true
    },
    {
        "id": 516,
        "identity_id": 516,
        "supplier_type_id": 2,
        "bic": "GKCCBEBB",
        "is_active": true
    },
    {
        "id": 517,
        "identity_id": 517,
        "supplier_type_id": 2,
        "bic": "CTBKBEBX",
        "is_active": true
    },
    {
        "id": 518,
        "identity_id": 518,
        "supplier_type_id": 2,
        "bic": "GEBABEBB",
        "is_active": true
    },
    {
        "id": 519,
        "identity_id": 519,
        "supplier_type_id": 2,
        "bic": "BYBBBEBB",
        "is_active": true
    },
    {
        "id": 520,
        "identity_id": 520,
        "supplier_type_id": 2,
        "bic": "AAMMBEMM",
        "is_active": true
    },
    {
        "id": 521,
        "identity_id": 521,
        "supplier_type_id": 2,
        "bic": "CVMCBEBB",
        "is_active": true
    },
    {
        "id": 522,
        "identity_id": 522,
        "supplier_type_id": 2,
        "bic": "AAFFBEFF",
        "is_active": true
    },
    {
        "id": 523,
        "identity_id": 523,
        "supplier_type_id": 2,
        "bic": "CRLYBEBB",
        "is_active": true
    },
    {
        "id": 524,
        "identity_id": 524,
        "supplier_type_id": 2,
        "bic": "CREGBEBB",
        "is_active": true
    },
    {
        "id": 525,
        "identity_id": 525,
        "supplier_type_id": 2,
        "bic": "CITIBEBX",
        "is_active": true
    },
    {
        "id": 526,
        "identity_id": 526,
        "supplier_type_id": 2,
        "bic": "COBABEBX",
        "is_active": true
    },
    {
        "id": 527,
        "identity_id": 527,
        "supplier_type_id": 2,
        "bic": "YYYYBEYY",
        "is_active": true
    },
    {
        "id": 528,
        "identity_id": 528,
        "supplier_type_id": 2,
        "bic": "NICABEBB",
        "is_active": true
    },
    {
        "id": 529,
        "identity_id": 529,
        "supplier_type_id": 2,
        "bic": "GOLABEB1",
        "is_active": true
    },
    {
        "id": 530,
        "identity_id": 530,
        "supplier_type_id": 2,
        "bic": "DEUTBEBE",
        "is_active": true
    },
    {
        "id": 531,
        "identity_id": 531,
        "supplier_type_id": 2,
        "bic": "DIERBE21",
        "is_active": true
    },
    {
        "id": 532,
        "identity_id": 532,
        "supplier_type_id": 2,
        "bic": "PRIBBEBB",
        "is_active": true
    },
    {
        "id": 533,
        "identity_id": 533,
        "supplier_type_id": 2,
        "bic": "MGTCBEBE",
        "is_active": true
    },
    {
        "id": 534,
        "identity_id": 534,
        "supplier_type_id": 2,
        "bic": "EURBBE99",
        "is_active": true
    },
    {
        "id": 535,
        "identity_id": 535,
        "supplier_type_id": 2,
        "bic": "HSBCBEBB",
        "is_active": true
    },
    {
        "id": 536,
        "identity_id": 536,
        "supplier_type_id": 2,
        "bic": "BBRUBEBB",
        "is_active": true
    },
    {
        "id": 537,
        "identity_id": 537,
        "supplier_type_id": 2,
        "bic": "AAQQBEQQ",
        "is_active": true
    },
    {
        "id": 538,
        "identity_id": 538,
        "supplier_type_id": 2,
        "bic": "KREDBEBB",
        "is_active": true
    },
    {
        "id": 539,
        "identity_id": 539,
        "supplier_type_id": 2,
        "bic": "KEYTBEBB",
        "is_active": true
    },
    {
        "id": 540,
        "identity_id": 540,
        "supplier_type_id": 2,
        "bic": "LOCYBEBB",
        "is_active": true
    },
    {
        "id": 541,
        "identity_id": 541,
        "supplier_type_id": 2,
        "bic": "MBWMBEBB",
        "is_active": true
    },
    {
        "id": 542,
        "identity_id": 542,
        "supplier_type_id": 2,
        "bic": "BOTKBEBX",
        "is_active": true
    },
    {
        "id": 543,
        "identity_id": 543,
        "supplier_type_id": 2,
        "bic": "NEECBEB2",
        "is_active": true
    },
    {
        "id": 544,
        "identity_id": 544,
        "supplier_type_id": 2,
        "bic": "DNIBBE21",
        "is_active": true
    },
    {
        "id": 545,
        "identity_id": 545,
        "supplier_type_id": 2,
        "bic": "PUILBEBB",
        "is_active": true
    },
    {
        "id": 546,
        "identity_id": 546,
        "supplier_type_id": 2,
        "bic": "RABOBE22",
        "is_active": true
    },
    {
        "id": 547,
        "identity_id": 547,
        "supplier_type_id": 2,
        "bic": "REVOBEB2",
        "is_active": true
    },
    {
        "id": 548,
        "identity_id": 548,
        "supplier_type_id": 2,
        "bic": "RCBPBEBB",
        "is_active": true
    },
    {
        "id": 549,
        "identity_id": 549,
        "supplier_type_id": 2,
        "bic": "BSCHBEBB",
        "is_active": true
    },
    {
        "id": 550,
        "identity_id": 550,
        "supplier_type_id": 2,
        "bic": "SAXBBEB1",
        "is_active": true
    },
    {
        "id": 551,
        "identity_id": 551,
        "supplier_type_id": 2,
        "bic": "SGABBEB2",
        "is_active": true
    },
    {
        "id": 552,
        "identity_id": 552,
        "supplier_type_id": 2,
        "bic": "IRVTBEBB",
        "is_active": true
    },
    {
        "id": 553,
        "identity_id": 553,
        "supplier_type_id": 2,
        "bic": "TRIOBEBB",
        "is_active": true
    },
    {
        "id": 554,
        "identity_id": 554,
        "supplier_type_id": 2,
        "bic": "BMPBBEBB",
        "is_active": true
    },
    {
        "id": 555,
        "identity_id": 555,
        "supplier_type_id": 2,
        "bic": "UTWBBEBB",
        "is_active": true
    },
    {
        "id": 556,
        "identity_id": 556,
        "supplier_type_id": 2,
        "bic": "VAPEBE22",
        "is_active": true
    },
    {
        "id": 557,
        "identity_id": 557,
        "supplier_type_id": 2,
        "bic": "FVLBBE22",
        "is_active": true
    },
    {
        "id": 558,
        "identity_id": 558,
        "supplier_type_id": 2,
        "bic": "VDSPBE91",
        "is_active": true
    },
    {
        "id": 559,
        "identity_id": 559,
        "supplier_type_id": 2,
        "bic": "TRWIBEB1",
        "is_active": true
    }
]
JSON;

$identities = json_decode($identities_json, true);
$banks = json_decode($banks_json, true);

$events = $orm->disableEvents();

/*
for($i = 0; $i < count($identities); $i++) {
    Identity::create($identities[$i]);
    Bank::create($banks[$i]);
}
*/



Identity::create([
        "id"=>518,
        "type_id"=>3,
        "legal_name"=>"BNP PARIBAS FORTIS",
        "short_name"=>"BNP PARIBAS FORTIS - FINTRO",
        "has_vat"=>true,
        "vat_number"=>"BE0403199702",
        "registration_number"=>"0403199702",
        "nationality"=>"BE",
        "address_street"=>"Rue Montagne du Parc, 3",
        "address_city"=>"Bruxelles",
        "address_zip"=>"1000",
        "address_country"=>"BE",
        "email"=>"info@bnpparibasfortis.com",
        "phone"=>"+3227622000",
        "bank_account_bic"=>"GEBABEBB",
        "is_active"=>true
    ]);
Bank::create([
        "id"=>518,
        "identity_id"=>518,
        "supplier_type_id"=>2,
        "bic"=>"GEBABEBB",
        "is_active"=>true,
        "address_street"=>"Rue Montagne du Parc, 3",
        "address_city"=>"Bruxelles",
        "address_zip"=>"1000",
        "address_country"=>"BE"
    ]);

$orm->enableEvents($events);

// sync values from Identities to Suppliers (Banks)
Bank::search(['object_class', '=', 'finance\bank\Bank'])->do('sync_from_identity');
