<?php

use identity\Identity;
use realestate\ownership\Owner;
use realestate\ownership\Ownership;

['orm' => $orm] = eQual::inject(['orm']);

$events = $orm->disableEvents();

Ownership::create([
    "id"=> 2,
    "description"=> "Charles Max",
    "condo_id"=> 1,
    "ownership_type"=> "unique",
    "total_shares"=> 100,
    "transfer_from_id"=> null,
    "transfer_to_id"=> null,
    "representative_identity_id"=> null,
    "has_representative"=> false,
    "date_from"=> strtotime("2020-01-01T00:00:00+00:00"),
]);

Ownership::create([
    "id"=> 3,
    "description"=> "Lucienne Prévaut",
    "condo_id"=> 1,
    "ownership_type"=> "unique",
    "total_shares"=> 100,
    "transfer_from_id"=> null,
    "transfer_to_id"=> null,
    "representative_identity_id"=> null,
    "has_representative"=> false,
    "date_from"=> strtotime("2010-01-01T00:00:00+00:00"),
]);

Ownership::create([
    "id"=> 4,
    "description"=> "Etienne Duchemin, Sarah Duchemin, Louis Duchemin",
    "condo_id"=> 1,
    "ownership_type"=> "unique",
    "total_shares"=> 100,
    "transfer_from_id"=> null,
    "transfer_to_id"=> null,
    "representative_identity_id"=> null,
    "has_representative"=> false,
    "date_from"=> strtotime("2020-01-01T00:00:00+00:00"),
]);

Ownership::create([
    "id"=> 5,
    "description"=> "Géraldine Desmet",
    "condo_id"=> 2,
    "ownership_type"=> "unique",
    "total_shares"=> 100,
    "transfer_from_id"=> null,
    "transfer_to_id"=> null,
    "representative_identity_id"=> null,
    "has_representative"=> false,
    "date_from"=> strtotime("2020-01-01T00:00:00+00:00"),
]);
Ownership::create([
    "id"=> 6,
    "description"=> "Raoul Ménart",
    "condo_id"=> 2,
    "ownership_type"=> "unique",
    "total_shares"=> 100,
    "transfer_from_id"=> null,
    "transfer_to_id"=> null,
    "representative_identity_id"=> null,
    "has_representative"=> false,
    "date_from"=> strtotime("2020-01-01T00:00:00+00:00"),
]);
Ownership::create([
    "id"=> 7,
    "description"=> "Roland Dupuis",
    "condo_id"=> 2,
    "ownership_type"=> "unique",
    "total_shares"=> 100,
    "transfer_from_id"=> null,
    "transfer_to_id"=> null,
    "representative_identity_id"=> null,
    "has_representative"=> false,
    "date_from"=> strtotime("2020-01-01T00:00:00+00:00"),
]);


Identity::create([
	"id" => 3,
	"type_id" => 1,
	"type" => "IN",
	"description" => null,
	"bank_account_iban" => "BE57429174466535",
	"bank_account_bic" => "KREDBEBB",
	"signature" => null,
	"legal_name" => null,
	"short_name" => null,
	"has_vat" => false,
	"vat_number" => null,
	"registration_number" => null,
	"citizen_identification" => "57.03.10-054.49",
	"nationality" => "BE",
	"has_parent" => false,
	"parent_id" => null,
	"firstname" => "Roland",
	"lastname" => "Dupuis",
	"gender" => "M",
	"title" => "Mr",
	"date_of_birth" => strtotime("1957-03-10T00:00:00+00:00"),
	"lang_id" => 2,
	"address_street" => "Avenue des platanes, 865",
	"address_dispatch" => null,
	"address_city" => "Forest",
	"address_zip" => "1190",
	"address_state" => null,
	"address_country" => "BE",
	"email" => "roland.dupuis@example.com",
	"email_alt" => null,
	"phone" => "+32487654312",
	"is_active" => true
]);
Identity::create([
	"id" => 4,
	"type_id" => 1,
	"type" => "IN",
	"description" => null,
	"bank_account_iban" => "BE15631611797630",
	"bank_account_bic" => "BBRUBEBB",
	"signature" => null,
	"legal_name" => null,
	"short_name" => null,
	"has_vat" => false,
	"vat_number" => null,
	"registration_number" => null,
	"citizen_identification" => "49.11.13-063.45",
	"nationality" => "BE",
	"has_parent" => false,
	"parent_id" => null,
	"firstname" => "Etienne",
	"lastname" => "Duchemin",
	"gender" => "M",
	"title" => "Mr",
	"date_of_birth" => strtotime("1949-11-13T00:00:00+00:00"),
	"lang_id" => 2,
	"address_street" => "Rue des Tisons, 12",
	"address_dispatch" => null,
	"address_city" => "Ixelles",
	"address_zip" => "10500",
	"address_state" => null,
	"address_country" => "BE",
	"email" => "etienne.duchemin@example.com",
	"email_alt" => null,
	"phone" => "+32476897643",
	"is_active" => true
]);
Identity::create([
	"id" => 5,
	"type_id" => 1,
	"type" => "IN",
	"description" => null,
	"bank_account_iban" => "BE72817729925416",
	"bank_account_bic" => "ISAEBEBB",
	"signature" => null,
	"legal_name" => null,
	"short_name" => null,
	"has_vat" => false,
	"vat_number" => null,
	"registration_number" => null,
	"citizen_identification" => "49.06.16-032.13",
	"nationality" => "BE",
	"has_parent" => false,
	"parent_id" => null,
	"firstname" => "Raoul",
	"lastname" => "Ménart",
	"gender" => "M",
	"title" => "Mr",
	"date_of_birth" => strtotime("1949-06-16T00:00:00+00:00"),
	"lang_id" => 2,
	"address_street" => "Impasse de Ciprès, 1",
	"address_dispatch" => "Entréé B",
	"address_city" => "Watermael-Boitsfort",
	"address_zip" => "1170",
	"address_state" => null,
	"address_country" => "BE",
	"email" => "raoul.menart@example.com",
	"email_alt" => null,
	"phone" => "+3226602982",
	"is_active" => true
]);
Identity::create([
	"id" => 6,
	"type_id" => 1,
	"type" => "IN",
	"description" => null,
	"bank_account_iban" => "BE24957376249238",
	"bank_account_bic" => "CTBKBEBX",
	"signature" => null,
	"legal_name" => null,
	"short_name" => null,
	"has_vat" => false,
	"vat_number" => null,
	"registration_number" => null,
	"citizen_identification" => "53.04.11-009-27",
	"nationality" => "BE",
	"has_parent" => false,
	"parent_id" => null,
	"firstname" => "Lucienne",
	"lastname" => "Prévaut",
	"gender" => "F",
	"title" => "Mrs",
	"date_of_birth" => strtotime("1953-04-11T00:00:00+00:00"),
	"lang_id" => 2,
	"address_street" => "Rue des Tisons, 12",
	"address_dispatch" => null,
	"address_city" => "Ixelles",
	"address_zip" => "1050",
	"address_state" => null,
	"address_country" => "BE",
	"email" => "luluprev@example.com",
	"email_alt" => null,
	"phone" => "+32487541312",
	"is_active" => true
]);
Identity::create([
	"id" => 7,
	"type_id" => 1,
	"type" => "IN",
	"description" => null,
	"bank_account_iban" => "BE87954697551394",
	"bank_account_bic" => "CTBKBEBX",
	"signature" => null,
	"legal_name" => null,
	"short_name" => null,
	"has_vat" => false,
	"vat_number" => null,
	"registration_number" => null,
	"citizen_identification" => "64.11.13-073-11",
	"nationality" => "BE",
	"has_parent" => false,
	"parent_id" => null,
	"firstname" => "Géraldine",
	"lastname" => "Desmet",
	"gender" => "F",
	"title" => "Mrs",
	"date_of_birth" => strtotime("1964-11-13T00:00:00+00:00"),
	"lang_id" => 1,
	"address_street" => "Rue des Églantiers, 14",
	"address_dispatch" => null,
	"address_city" => "Ixelles",
	"address_zip" => "1050",
	"address_state" => null,
	"address_country" => "BE",
	"email" => "g.desmet@example.com",
	"email_alt" => null,
	"phone" => "+32497865413",
	"is_active" => true
]);
Identity::create([
	"id" => 8,
	"type_id" => 1,
	"type" => "IN",
	"description" => null,
	"bank_account_iban" => "BE02798589189440",
	"bank_account_bic" => "GKCCBEBB",
	"signature" => null,
	"legal_name" => null,
	"short_name" => null,
	"has_vat" => false,
	"vat_number" => null,
	"registration_number" => null,
	"citizen_identification" => "75.01.10-002-15",
	"nationality" => "BE",
	"has_parent" => false,
	"parent_id" => null,
	"firstname" => "Sarah",
	"lastname" => "Duchemin",
	"gender" => "F",
	"title" => "Mrs",
	"date_of_birth" => strtotime("1975-01-10T00:00:00+00:00"),
	"lang_id" => 2,
	"address_street" => "Allée des Épicéas, 35",
	"address_dispatch" => null,
	"address_city" => "Overijse",
	"address_zip" => "3090",
	"address_state" => null,
	"address_country" => "BE",
	"email" => "sar.duch@example.com",
	"email_alt" => null,
	"phone" => "+32456765432",
	"is_active" => true
]);
Identity::create([
	"id" => 9,
	"type_id" => 1,
	"type" => "IN",
	"description" => null,
	"bank_account_iban" => "BE15485649427730",
	"bank_account_bic" => "KREDBEBB",
	"signature" => null,
	"legal_name" => null,
	"short_name" => null,
	"has_vat" => false,
	"vat_number" => null,
	"registration_number" => null,
	"citizen_identification" => "78.09.27-543-11",
	"nationality" => "BE",
	"has_parent" => false,
	"parent_id" => null,
	"firstname" => "Louis",
	"lastname" => "Duchemin",
	"gender" => "M",
	"title" => "Mr",
	"date_of_birth" => strtotime("1978-09-27T00:00:00+00:00"),
	"lang_id" => 2,
	"address_street" => "Place des Tilleuls, 3",
	"address_dispatch" => null,
	"address_city" => "Forest",
	"address_zip" => "1190",
	"address_state" => null,
	"address_country" => "BE",
	"email" => "l.duch@example.com",
	"email_alt" => null,
	"phone" => null,
	"is_active" => true
]);
Identity::create([
	"id" => 10,
	"type_id" => 1,
	"type" => "IN",
	"description" => null,
	"bank_account_iban" => null,
	"bank_account_bic" => null,
	"signature" => null,
	"legal_name" => null,
	"short_name" => null,
	"has_vat" => false,
	"vat_number" => null,
	"registration_number" => null,
	"citizen_identification" => "87.08.03-077-21",
	"nationality" => "BE",
	"has_parent" => false,
	"parent_id" => null,
	"firstname" => "Charles",
	"lastname" => "MAX",
	"gender" => "M",
	"title" => "Mr",
	"date_of_birth" => strtotime("1987-08-03T00:00:00+00:00"),
	"lang_id" => 2,
	"address_street" => "Rue des Tisons, 12",
	"address_dispatch" => null,
	"address_city" => "Ixelles",
	"address_zip" => "1050",
	"address_state" => null,
	"address_country" => "BE",
	"email" => "charles.max@example.com",
	"email_alt" => null,
	"phone" => null,
	"is_active" => true
]);
Identity::create([
	"id" => 11,
	"type_id" => 1,
	"type" => "IN",
	"description" => null,
	"bank_account_iban" => "BE97429842933749",
	"bank_account_bic" => "KREDBEBB",
	"signature" => null,
	"legal_name" => null,
	"short_name" => null,
	"has_vat" => false,
	"vat_number" => null,
	"registration_number" => null,
	"citizen_identification" => "62.12.01-076.99",
	"nationality" => "BE",
	"has_parent" => false,
	"parent_id" => null,
	"firstname" => "Jacques",
	"lastname" => "BONPREZ",
	"gender" => "M",
	"title" => "Mr",
	"date_of_birth" => strtotime("1962-12-01T00:00:00+00:00"),
	"lang_id" => 2,
	"address_street" => "Rue des Hêtres, 65",
	"address_dispatch" => null,
	"address_city" => "Ixelles",
	"address_zip" => "1050",
	"address_state" => null,
	"address_country" => "BE",
	"email" => "jacquesbonprez@example.com",
	"email_alt" => null,
	"phone" => null,
	"is_active" => true
]);
Identity::create([
	"id" => 12,
	"type_id" => 1,
	"type" => "IN",
	"description" => null,
	"bank_account_iban" => null,
	"bank_account_bic" => null,
	"signature" => null,
	"legal_name" => null,
	"short_name" => null,
	"has_vat" => false,
	"vat_number" => null,
	"registration_number" => null,
	"citizen_identification" => "63.12.02-034.47",
	"nationality" => "BE",
	"has_parent" => false,
	"parent_id" => null,
	"firstname" => "Suzanne",
	"lastname" => "BONPREZ",
	"gender" => "F",
	"title" => "Mrs",
	"date_of_birth" => strtotime("1963-12-02T00:00:00+00:00"),
	"lang_id" => 2,
	"address_street" => null,
	"address_dispatch" => null,
	"address_city" => null,
	"address_zip" => null,
	"address_state" => null,
	"address_country" => "BE",
	"email" => "suzannebonprez@example.com",
	"email_alt" => null,
	"phone" => null,
	"is_active" => true
]);


// Roland Dupuis
Owner::create([
    "id" => 3,
    "condo_id" => 2,
    "ownership_id" => 7,
    "owner_shares" => 100,
    "owner_type" => "full",
    "identity_id" => 3
]);
// Etienne Duchemin
Owner::create([
    "id" => 4,
    "condo_id" => 1,
    "ownership_id" => 4,
    "owner_shares" => 100,
    "owner_type" => "usufruct",
    "identity_id" => 4
]);
// Raoul Ménart
Owner::create([
    "id" => 5,
    "condo_id" => 2,
    "ownership_id" => 6,
    "owner_shares" => 100,
    "owner_type" => "full",
    "identity_id" => 5
]);
// Lucienne Prévaut
Owner::create([
    "id" => 6,
    "condo_id" => 1,
    "ownership_id" => 3,
    "owner_shares" => 100,
    "owner_type" => "full",
    "identity_id" => 6
]);
// Géraldine Desmet
Owner::create([
    "id" => 7,
    "condo_id" => 2,
    "ownership_id" => 5,
    "owner_shares" => 100,
    "owner_type" => "full",
    "identity_id" => 7
]);
// Sarah Duchemin
Owner::create([
    "id" => 8,
    "condo_id" => 1,
    "ownership_id" => 4,
    "owner_shares" => 50,
    "owner_type" => "bare",
    "identity_id" => 8
]);
// Louis Duchemin
Owner::create([
    "id" => 9,
    "condo_id" => 1,
    "ownership_id" => 4,
    "owner_shares" => 50,
    "owner_type" => "bare",
    "identity_id" => 9
]);
// Charles Max
Owner::create([
    "id" => 10,
    "condo_id" => 1,
    "ownership_id" => 2,
    "owner_shares" => 100,
    "owner_type" => "full",
    "identity_id" => 10
]);



$orm->enableEvents($events);

// sync values from Identities to Owners
Owner::search()->do('sync_from_identity');